config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views import defaults as default_views
from django.views.generic import TemplateView

from config.sitemaps import (
    BookSitemap,
    BookGenreSitemap,
    BookTagSitemap,
    BookChapterSitemap,
    StaticViewSitemap,
)
from .www_verif import GoogleSearchVerif, YandexSearchVerif

sitemaps = {
    'books': BookSitemap,
    'bookgenres': BookGenreSitemap,
    'booktags': BookTagSitemap,
    'bookchapters': BookChapterSitemap,
    'static_urls': StaticViewSitemap,
}

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Sitemap
    # path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps},
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # Search verification
    path(f'google{settings.WEBMASTER_VERIFICATION["google"]}.html', GoogleSearchVerif.as_view()),
    path(f'yandex_{settings.WEBMASTER_VERIFICATION["yandex"]}.html', YandexSearchVerif.as_view()),
    # User management
    path(
        "users/",
        include("novel.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    path("comments/", include("django_comments_xtd.urls")),
    path("summernote/", include("django_summernote.urls")),
    # Your stuff: custom urls includes go here
    path("", include("novel.books.urls")),
    path("contact-us/", TemplateView.as_view(template_name='pages/contact-us.html'), name='contact-us'),
    path("advertisement/", TemplateView.as_view(template_name='pages/advertisement.html'), name='advertisement'),
    path("send-feedback/", TemplateView.as_view(template_name='pages/send-feedback.html'), name='send-feedback'),
    path("report-problem/", TemplateView.as_view(template_name='pages/report-problem.html'), name='report-problem'),
    path("privacy-policy/", TemplateView.as_view(template_name='pages/privacy-policy.html'), name='privacy-policy'),
    path("terms-conditions/", TemplateView.as_view(template_name='pages/terms-conditions.html'), name='terms-conditions'),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

novel/books/urls.py
from django.urls import path

from .apps import BooksConfig
from .views import FrontPageView, BookGenreView, BookTagView, BookView, BookChapterView, BookRankingView, BookSearchView, book_vote_view, book_vote_ajax_view, session_theme_ajax_view

app_name = BooksConfig.verbose_name

urlpatterns = [
    path("", FrontPageView.as_view(), name="front_page"),
    path("category/all/", BookGenreView.as_view(), name="genre-list"),
    path(
        "category/<slug:bookgenre_slug>/",
        BookGenreView.as_view(),
        name="genre"
    ),
    path("tags/all/", BookTagView.as_view(), name="tag-list"),
    path("tags/<slug:booktag_slug>/", BookTagView.as_view(), name="tag"),
    path("books/<slug:book_slug>/", BookView.as_view(), name="book"),
    path("books/<slug:book_slug>/<int:c_id>/", BookChapterView.as_view(), name="bookchapter"),
    path("books/<slug:book_slug>/vote/", book_vote_view, name="vote"),
    path("books/<slug:book_slug>/vote-ajax/", book_vote_ajax_view, name="vote-ajax"),
    path("ranking/", BookRankingView.as_view(), name="ranking"),
    path("search/", BookSearchView.as_view(), name="search"),
    path("ajax/session-theme/", session_theme_ajax_view, name="session-theme-ajax"),
]

novel/users/urls.py
from django.urls import path

from novel.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    library_view,
    add_library_book,
    remove_library_book,
    add_remove_library_book_ajax,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<str:username>/library/", view=library_view, name="library"),
    path("library/<slug:book_slug>/add/", view=add_library_book, name="library-add"),
    path("library/<slug:book_slug>/remove/", view=remove_library_book, name="library-remove"),
    path("library/<slug:book_slug>/lib-add-remove-ajax/", view=add_remove_library_book_ajax, name="lib-add-remove-ajax")
]

novel/comments/models.py
from django.db import models
from django_comments_xtd.models import XtdComment

from .managers import CustomCommentManager


class CustomComment(XtdComment):
    user_avatar = models.CharField(default='users/default.png', blank=True, max_length=255)

novel/books/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from django_comments_xtd.forms import XtdCommentForm
from django_comments_xtd.models import TmpXtdComment


class BookSearchForm(forms.Form):
    search_field = forms.CharField(
        label='Search book:', max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': 'Search book',
            'class': 'form-control',
        })
    )


class BookCommentForm(XtdCommentForm):
    avatar = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': _('avatar')})
    )

    def get_comment_create_data(self, *args, **kwargs):
        data = super(BookCommentForm, self).get_comment_create_data(*args, **kwargs)
        data.update({'avatar': self.cleaned_data['avatar']})
        print(self.user)
        print(data)
        return data

novel/comments/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

from django_comments_xtd.forms import XtdCommentForm
from django_comments_xtd.models import TmpXtdComment

User = get_user_model()


class CustomCommentForm(XtdCommentForm):
    user_avatar = forms.CharField(
        required=False,
        max_length=255,
        widget=forms.HiddenInput(),
        initial='/users/default.png',
    )

    def get_comment_create_data(self, **kwargs):
        data = super(CustomCommentForm, self).get_comment_create_data(**kwargs)
        try:
            user = User.objects.get(email=data['user_email'])
            data.update({
                'user_name': user.username,
                'user_avatar': user.profile.avatar,
            })
        except User.DoesNotExist:
            data.update({
                'user_name': data.get('user_name', 'Guest')
            })
        return data

novel/books/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchVector
from django.db.models import F
from django.http import JsonResponse, HttpResponse
# from django.utils.decorators import method_decorator
from django.urls import reverse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
# from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.vary import vary_on_headers
from django.views.generic import View, DetailView, ListView

from novel.users.models import BookProgress
from .models import Book, BookTag, BookChapter
from .forms import BookSearchForm
from .filters import BookFilter
from .utils import capitalize_slug


class FrontPageView(View):
    def get(self, request, *args, **kwargs):
        books = Book.objects.published().select_related('bookgenre').filter(recommended=True).random_qslist(only=12)
        b_chaps = BookChapter.objects.order_by('book_id', '-created').distinct('book_id').values_list('id', flat=True)
        b_chaps = BookChapter.objects.select_related('book').filter(id__in=b_chaps).order_by('-created')
        promo_title = 'Read your favourite novels in one place'
        promo_subtitle = 'Get access to the latest releases of novels and light-novels'
        paginator = Paginator(b_chaps, 10)
        page = self.request.GET.get('page')
        b_chaps = paginator.get_page(page)
        context = {'books': books, 'b_chaps': b_chaps, 'promo_title': promo_title, 'promo_subtitle': promo_subtitle}

        return render(request, template_name='books/front_page.html', context=context)


class BookGenreView(ListView):
    template_name = 'books/bookgenre.html'

    def get(self, request, *args, **kwargs):
        p = 'page'
        p_num = 16
        try:
            # query params without page
            f_params = '&'.join({f'{k}={v}' if k != p else '' for (k, v) in request.GET.items()})
            f_params = '' if not f_params else '&' + f_params
            books = Book.objects.published().select_related('bookgenre').prefetch_related('booktag').order_by('-votes')
            if kwargs:
                books = books.filter(bookgenre__slug=kwargs['bookgenre_slug'])
            f = BookFilter(request.GET, queryset=books)
            paginator = Paginator(list(f.qs), p_num)
            page = request.GET.get(p)
            f_books = paginator.get_page(page)
            context = {
                'f_params': f_params,
                'f_form': f.form,
                'f_books': f_books,
            }
            return render(request, template_name=self.template_name, context=context)
        except Book.DoesNotExist:
            return redirect('/404/')


class BookTagView(ListView):
    template_name = 'books/booktag.html'

    def get(self, request, *args, **kwargs):
        p = 'page'
        p_num = 16
        try:
            tags = BookTag.objects.all()
            context = {'tags': tags}
            if kwargs:
                # query params without page
                f_params = '&'.join({f'{k}={v}' if k != p else '' for (k, v) in request.GET.items()})
                f_params = '' if not f_params else '&' + f_params
                tag_name = capitalize_slug(kwargs['booktag_slug'])
                books = Book.objects.published().filter(booktag__slug=kwargs['booktag_slug'])
                books = books.select_related('bookgenre').prefetch_related('booktag').order_by('-votes')
                f = BookFilter(request.GET, queryset=books)
                paginator = Paginator(list(f.qs), p_num)
                page = request.GET.get(p)
                f_books = paginator.get_page(page)
                context['tag_name'] = tag_name
                context['f_params'] = f_params
                context['f_form'] = f.form
                context['f_books'] = f_books
            return render(request, template_name=self.template_name, context=context)
        except BookTag.DoesNotExist:
            return redirect('/404/')


class BookView(DetailView):
    template_name = 'books/book.html'

    @vary_on_headers('X-Requested-With')
    def get(self, request, *args, **kwargs):
        try:
            book = Book.objects.select_related('bookgenre').prefetch_related('booktag').get(slug=kwargs['book_slug'])
            user_auth = request.user.is_authenticated

            if request.is_ajax():
                data = {}
                bookchapters = list(book.bookchapters.values_list(
                    'c_id', 'title', 'created', named=True).order_by('c_id'))
                last_chap = bookchapters[-1] if len(bookchapters) >= 1 else None
                template_name = 'books/book_chap_nav.html'
                context = {
                    'book': book,
                    'bookchapters': bookchapters,
                    'last_chap': last_chap,
                }
                data['html_chaps'] = render_to_string(
                    template_name,
                    context=context,
                    request=request
                )
                return JsonResponse(data)

            context = {
                'book': book,
                'next': reverse('comments-xtd-sent'),
                'user_auth': user_auth
            }
            if book.similar:
                similar_books = Book.objects.filter(id__in=book.similar).order_by('pk')
                context.update({'similar_books': similar_books})
            if user_auth:
                book_prog = False
                context['user_lib'] = list(request.user.library.book.all())
                try:
                    book_prog = BookProgress.objects.get(user=request.user, book=book)
                    context['book_prog'] = book_prog
                except BookProgress.DoesNotExist:
                    context['book_prog'] = book_prog
            return render(request, template_name=self.template_name, context=context)
        except Book.DoesNotExist:
            return redirect('/404/')


class BookChapterView(DetailView):
    template_name = 'books/bookchapter.html'

    @vary_on_headers('X-Requested-With')
    def get(self, request, *args, **kwargs):
        try:
            b_chap = BookChapter.objects.select_related('book').get(book__slug=kwargs['book_slug'], c_id=kwargs['c_id'])
            b_chaps = BookChapter.objects.filter(book__slug=kwargs['book_slug']).values('c_id', 'title', 'created').order_by('c_id')
            for chap in b_chaps:
                url = reverse('books:bookchapter', kwargs={'book_slug': b_chap.book.slug, 'c_id': chap['c_id']})
                chap.update({'absolute_url': url})

            try:
                prev_chap = b_chaps[kwargs['c_id'] - 2:kwargs['c_id'] - 1][0]
            except (IndexError, AssertionError):
                prev_chap = None
            try:
                next_chap = b_chaps[kwargs['c_id']:kwargs['c_id'] + 2][0]
            except IndexError:
                next_chap = None

            if request.is_ajax():
                data = {}
                template_name = 'books/bookchapter_chap_nav.html'
                context = {'b_chap': b_chap, 'b_chaps': b_chaps}
                data['html_chaps'] = render_to_string(
                    template_name,
                    context=context,
                    request=request
                )
                return JsonResponse(data)

            context = {
                'b_chap': b_chap,
                'prev_chap': prev_chap,
                'next_chap': next_chap,
            }

            if request.user.is_authenticated:
                context['user_lib'] = list(request.user.library.book.all())
                try:
                    book_prog = BookProgress.objects.get(user=request.user, book=b_chap.book)
                    if book_prog.c_id != b_chap.c_id:
                        book_prog.c_id = b_chap.c_id
                        book_prog.save()
                except BookProgress.DoesNotExist:
                    BookProgress.objects.create(
                        book=b_chap.book,
                        user=request.user,
                        c_id=b_chap.c_id,
                    )
            return render(request, template_name=self.template_name, context=context)
        except (Book.DoesNotExist, BookChapter.DoesNotExist):
            return redirect('/404/')


class BookRankingView(ListView):
    template_name = 'books/bookranking.html'
    queryset = Book.objects.published().filter(ranking__gt=0).order_by('ranking')
    context_object_name = 'books_all'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = list(self.queryset.iterator())
        user_auth = self.request.user.is_authenticated
        books = qs[3:]
        books_top = qs[:3]
        paginator = Paginator(books, 7)
        page = self.request.GET.get('page')
        books = paginator.get_page(page)
        context = {
            'books': books, 'books_top': books_top,
            'page_title': 'Ranking',
            'user_auth': user_auth,
        }
        if user_auth:
            user_lib = list(self.request.user.library.book.all())
            context['user_lib'] = user_lib
        return context


class BookSearchView(ListView):
    template_name = 'books/booksearch.html'
    form = BookSearchForm
    context = {'form': form, 'page_title': 'Search Books'}

    def get(self, request, **kwargs):
        form = self.form(request.GET)
        context = dict(self.context)  # update get view context
        context['form'] = form

        if request.is_ajax():
            data = {}
            template_name = 'books/booksearch-result.html'
            search_field = request.GET.get('search_field', None)

            if not search_field:
                # handle ajax error
                return JsonResponse(data, status=403)

novel/comments/views.py
from django.shortcuts import render

# Create your views here.

novel/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<div class="container">
  <h1>Forbidden (403)</h1>

  <p>CSRF verification failed. Request aborted.</p>
</div>
{% endblock content %}

novel/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Novel To Read{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    <!-- <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/favicon180x180.ico' %}"> -->

    {% block css %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/selectize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.min.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  {% with req_cookie=request.COOKIES %}
  {% if request.resolver_match.url_name == "bookchapter" %}
    <body class="
      {{req_cookie.tm_color}}
      {{req_cookie.tm_font}}
      {{req_cookie.tm_fz}}
      {{req_cookie.tm_lh}}
    ">
  {% else %}
    <body>
  {% endif %}
  {% endwith %}

    <header class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container">

          <a class="navbar-brand" href="{% url 'books:front_page' %}">novelVerse</a>

          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% with url_name=request.resolver_match.url_name %}
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle{% if url_name == 'genre-list' or url_name == 'genre' %} active{% endif %}" href="{% url 'books:genre-list' %}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Browse</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item {% if url_name == 'genre-list' %} active{% endif %}" href="{% url 'books:genre-list' %}">All Genres</a>
                  <a class="dropdown-item {% if url_name == 'tag-list' %} active{% endif %}" href="{% url 'books:tag-list' %}">All Tags</a>
                  {% for bookgenre in bookgenres %}
                    <a class="dropdown-item{% if request.path == bookgenre.get_absolute_url %} active{% endif %}" href="{{bookgenre.get_absolute_url}}">{{bookgenre.name}}</a>
                  {% endfor %}

                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'ranking' %} active{% endif %}" href="{% url 'books:ranking' %}" href="{% url 'books:ranking' %}">Ranking</a>
              </li>
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'search' %} active{% endif %}" href="{% url 'books:search' %}">Search</a>
              </li>
            </ul>
            <ul class="navbar-nav mr-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:library' request.user.username %}">Library</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)" role="button" aria-haspopup="true" aria-expanded="false">
                    {{request.user.username}}
                  </a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'users:detail' request.user.username  %}">
                      {# URL provided by django-allauth/account/urls.py #}
                      {% trans "My Profile" %}
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">
                      {# URL provided by django-allauth/account/urls.py #}
                      {% trans "Sign Out" %}
                    </a>
                  </div>
                </li>
              {% else %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
              {% endif %}
            </ul>
            {% endwith %}
          </div>
        </div>
      </nav>
    </header>

    <div class="container alert-container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

    </div> <!-- container -->

    <main>
      {% load django_bootstrap_breadcrumbs %}

      {% block breadcrumbs %}
          {% clear_breadcrumbs %}
          {% breadcrumb "Home" "books:front_page" %}
      {% endblock %}

      {% block content %}
        {% render_breadcrumbs %}
        <p>Default new page.</p>
      {% endblock content %}

      {% block modal %}{% endblock modal %}
    </main>


    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="footer__col brand">
              <a class="navbar-brand" href="{% url 'books:front_page' %}">
                novelVerse
              </a>
              <span>© {% now "Y" %} novelVerse</span>
            </div>
          </div>
          <div class="col-md-3">
            <div class="footer__col">
              <h4 class="footer__col--title h4-title">Contacts</h4>
              {% url 'contact-us' as contact_us_url %}
              <a class="{% if request.path == contact_us_url %}active{% endif %}" href="{{contact_us_url}}">Contact Us</a>
              {% url 'advertisement' as advertisement_url %}
              <a class="{% if request.path == advertisement_url %}active{% endif %}" href="{{advertisement_url}}">Advertisement</a>
              {% url 'report-problem' as report_problem_url %}
              <a class="{% if request.path == report_problem_url %}active{% endif %}" href="{{report_problem_url}}">Report Problem</a>
              {% url 'send-feedback' as send_feedback_url %}
              <a class="{% if request.path == send_feedback_url %}active{% endif %}" href="{{send_feedback_url}}">Send Feedback</a>
            </div>
          </div>
          <div class="col-md-3">
            <div class="footer__col">
              <h4 class="footer__col--title h4-title">Genres</h4>
                {% for bookgenre in bookgenres %}
                  <a class="{% if request.path == bookgenre.get_absolute_url %}active{% endif %}" href="{{bookgenre.get_absolute_url}}">{{bookgenre.name}}</a>
                {% endfor %}
            </div>
          </div>
          <div class="col-md-3">
            <div class="footer__col">
              <h4 class="footer__col--title h4-title">Pages</h4>
              {% comment %}
              <a class="{% if request.path == '' %}active{% endif %}" href="">Premium</a>
              <a class="{% if request.path == '' %}active{% endif %}" href="">Daily Missions</a>
              <a class="{% if request.path == '' %}active{% endif %}" href="">Referral</a>
              {% endcomment %}
              {% url 'privacy-policy' as privacy_url %}
              <a class="{% if request.path == privacy_url %}active{% endif %}" href="{{privacy_url}}">Privacy Policy</a>
              {% url 'terms-conditions' as terms_url %}
              <a class="{% if request.path == terms_url %}active{% endif %}" href="{{terms_url}}">Terms and Conditions</a>
            </div>
          </div>
        </div>
      </div>
    </footer>

    {% block javascript %}
      <script type="text/javascript" src="{% static 'js/libs.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/project.min.js' %}"></script>
    {% endblock javascript %}

  </body>
</html>

novel/templates/google-verification.html
google-site-verification: google{{search_verif_code}}.html

novel/templates/yandex-verification.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>Verification: {{search_verif_code}}</body>
</html>