config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views import defaults as default_views
from django.views.generic import TemplateView

from config.sitemaps import (
    BookSitemap,
    BookGenreSitemap,
    BookTagSitemap,
    BookChapterSitemap,
    StaticViewSitemap,
)
from .www_verif import GoogleSearchVerif, YandexSearchVerif

sitemaps = {
    'books': BookSitemap,
    'bookgenres': BookGenreSitemap,
    'booktags': BookTagSitemap,
    'bookchapters': BookChapterSitemap,
    'static_urls': StaticViewSitemap,
}

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Sitemap
    # path('sitemap.xml', cache_page(86400)(sitemap), {'sitemaps': sitemaps},
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # Search verification
    path(f'google{settings.WEBMASTER_VERIFICATION["google"]}.html', GoogleSearchVerif.as_view()),
    path(f'yandex_{settings.WEBMASTER_VERIFICATION["yandex"]}.html', YandexSearchVerif.as_view()),
    # User management
    path(
        "users/",
        include("novel.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    path("comments/", include("django_comments_xtd.urls")),
    path("summernote/", include("django_summernote.urls")),
    # Your stuff: custom urls includes go here
    path("", include("novel.books.urls")),
    path("contact-us/", TemplateView.as_view(template_name='pages/contact-us.html'), name='contact-us'),
    path("advertisement/", TemplateView.as_view(template_name='pages/advertisement.html'), name='advertisement'),
    path("send-feedback/", TemplateView.as_view(template_name='pages/send-feedback.html'), name='send-feedback'),
    path("report-problem/", TemplateView.as_view(template_name='pages/report-problem.html'), name='report-problem'),
    path("privacy-policy/", TemplateView.as_view(template_name='pages/privacy-policy.html'), name='privacy-policy'),
    path("terms-conditions/", TemplateView.as_view(template_name='pages/terms-conditions.html'), name='terms-conditions'),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

novel/books/urls.py
from django.urls import path

from .apps import BooksConfig
from .views import FrontPageView, BookGenreView, BookTagView, BookView, BookChapterView, BookRankingView, BookSearchView, book_vote_view, book_vote_ajax_view, session_theme_ajax_view

app_name = BooksConfig.verbose_name

urlpatterns = [
    path("", FrontPageView.as_view(), name="front_page"),
    path("category/all/", BookGenreView.as_view(), name="genre-list"),
    path(
        "category/<slug:bookgenre_slug>/",
        BookGenreView.as_view(),
        name="genre"
    ),
    path("tags/all/", BookTagView.as_view(), name="tag-list"),
    path("tags/<slug:booktag_slug>/", BookTagView.as_view(), name="tag"),
    path("books/<slug:book_slug>/", BookView.as_view(), name="book"),
    path("books/<slug:book_slug>/<int:c_id>/", BookChapterView.as_view(), name="bookchapter"),
    path("books/<slug:book_slug>/vote/", book_vote_view, name="vote"),
    path("books/<slug:book_slug>/vote-ajax/", book_vote_ajax_view, name="vote-ajax"),
    path("ranking/", BookRankingView.as_view(), name="ranking"),
    path("search/", BookSearchView.as_view(), name="search"),
    path("ajax/session-theme/", session_theme_ajax_view, name="session-theme-ajax"),
]

novel/users/urls.py
from django.urls import path

from novel.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
    library_view,
    add_library_book,
    remove_library_book,
    add_remove_library_book_ajax,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<str:username>/library/", view=library_view, name="library"),
    path("library/<slug:book_slug>/add/", view=add_library_book, name="library-add"),
    path("library/<slug:book_slug>/remove/", view=remove_library_book, name="library-remove"),
    path("library/<slug:book_slug>/lib-add-remove-ajax/", view=add_remove_library_book_ajax, name="lib-add-remove-ajax")
]

novel/comments/models.py
from django.db import models
from django_comments_xtd.models import XtdComment

from .managers import CustomCommentManager


class CustomComment(XtdComment):
    user_avatar = models.CharField(default='users/default.png', blank=True, max_length=255)

novel/books/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from django_comments_xtd.forms import XtdCommentForm
from django_comments_xtd.models import TmpXtdComment


class BookSearchForm(forms.Form):
    search_field = forms.CharField(
        label='Search book:', max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': 'Search book',
            'class': 'form-control',
        })
    )


class BookCommentForm(XtdCommentForm):
    avatar = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': _('avatar')})
    )

    def get_comment_create_data(self, *args, **kwargs):
        data = super(BookCommentForm, self).get_comment_create_data(*args, **kwargs)
        data.update({'avatar': self.cleaned_data['avatar']})
        print(self.user)
        print(data)
        return data

novel/comments/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

from django_comments_xtd.forms import XtdCommentForm
from django_comments_xtd.models import TmpXtdComment

User = get_user_model()


class CustomCommentForm(XtdCommentForm):
    user_avatar = forms.CharField(
        required=False,
        max_length=255,
        widget=forms.HiddenInput(),
        initial='/users/default.png',
    )

    def get_comment_create_data(self, **kwargs):
        data = super(CustomCommentForm, self).get_comment_create_data(**kwargs)
        try:
            user = User.objects.get(email=data['user_email'])
            data.update({
                'user_name': user.username,
                'user_avatar': user.profile.avatar,
            })
        except User.DoesNotExist:
            data.update({
                'user_name': data.get('user_name', 'Guest')
            })
        return data

novel/books/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchVector
from django.db.models import F
from django.http import JsonResponse, HttpResponse
# from django.utils.decorators import method_decorator
from django.urls import reverse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
# from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.vary import vary_on_headers
from django.views.generic import View, DetailView, ListView

from novel.users.models import BookProgress
from .models import Book, BookTag, BookChapter
from .forms import BookSearchForm
from .filters import BookFilter
from .utils import capitalize_slug


class FrontPageView(View):
    def get(self, request, *args, **kwargs):
        books = Book.objects.published().select_related('bookgenre').filter(recommended=True).random_qslist(only=12)
        b_chaps = BookChapter.objects.order_by('book_id', '-created').distinct('book_id').values_list('id', flat=True)
        b_chaps = BookChapter.objects.select_related('book').filter(id__in=b_chaps).order_by('-created')
        promo_title = 'Read your favourite novels in one place'
        promo_subtitle = 'Get access to the latest releases of novels and light-novels'
        paginator = Paginator(b_chaps, 10)
        page = self.request.GET.get('page')
        b_chaps = paginator.get_page(page)
        context = {'books': books, 'b_chaps': b_chaps, 'promo_title': promo_title, 'promo_subtitle': promo_subtitle}

        return render(request, template_name='books/front_page.html', context=context)


class BookGenreView(ListView):
    template_name = 'books/bookgenre.html'

    def get(self, request, *args, **kwargs):
        p = 'page'
        p_num = 16
        try:
            # query params without page
            f_params = '&'.join({f'{k}={v}' if k != p else '' for (k, v) in request.GET.items()})
            f_params = '' if not f_params else '&' + f_params
            books = Book.objects.published().select_related('bookgenre').prefetch_related('booktag').order_by('-votes')
            if kwargs:
                books = books.filter(bookgenre__slug=kwargs['bookgenre_slug'])
            f = BookFilter(request.GET, queryset=books)
            paginator = Paginator(list(f.qs), p_num)
            page = request.GET.get(p)
            f_books = paginator.get_page(page)
            context = {
                'f_params': f_params,
                'f_form': f.form,
                'f_books': f_books,
            }
            return render(request, template_name=self.template_name, context=context)
        except Book.DoesNotExist:
            return redirect('/404/')


class BookTagView(ListView):
    template_name = 'books/booktag.html'

    def get(self, request, *args, **kwargs):
        p = 'page'
        p_num = 16
        try:
            tags = BookTag.objects.all()
            context = {'tags': tags}
            if kwargs:
                # query params without page
                f_params = '&'.join({f'{k}={v}' if k != p else '' for (k, v) in request.GET.items()})
                f_params = '' if not f_params else '&' + f_params
                tag_name = capitalize_slug(kwargs['booktag_slug'])
                books = Book.objects.published().filter(booktag__slug=kwargs['booktag_slug'])
                books = books.select_related('bookgenre').prefetch_related('booktag').order_by('-votes')
                f = BookFilter(request.GET, queryset=books)
                paginator = Paginator(list(f.qs), p_num)
                page = request.GET.get(p)
                f_books = paginator.get_page(page)
                context['tag_name'] = tag_name
                context['f_params'] = f_params
                context['f_form'] = f.form
                context['f_books'] = f_books
            return render(request, template_name=self.template_name, context=context)
        except BookTag.DoesNotExist:
            return redirect('/404/')


class BookView(DetailView):
    template_name = 'books/book.html'

    @vary_on_headers('X-Requested-With')
    def get(self, request, *args, **kwargs):
        try:
            book = Book.objects.select_related('bookgenre').prefetch_related('booktag').get(slug=kwargs['book_slug'])
            user_auth = request.user.is_authenticated

            if request.is_ajax():
                data = {}
                bookchapters = list(book.bookchapters.values_list(
                    'c_id', 'title', 'created', named=True).order_by('c_id'))
                last_chap = bookchapters[-1] if len(bookchapters) >= 1 else None
                template_name = 'books/book_chap_nav.html'
                context = {
                    'book': book,
                    'bookchapters': bookchapters,
                    'last_chap': last_chap,
                }
                data['html_chaps'] = render_to_string(
                    template_name,
                    context=context,
                    request=request
                )
                return JsonResponse(data)

            context = {
                'book': book,
                'next': reverse('comments-xtd-sent'),
                'user_auth': user_auth
            }
            if book.similar:
                similar_books = Book.objects.filter(id__in=book.similar).order_by('pk')
                context.update({'similar_books': similar_books})
            if user_auth:
                book_prog = False
                context['user_lib'] = list(request.user.library.book.all())
                try:
                    book_prog = BookProgress.objects.get(user=request.user, book=book)
                    context['book_prog'] = book_prog
                except BookProgress.DoesNotExist:
                    context['book_prog'] = book_prog
            return render(request, template_name=self.template_name, context=context)
        except Book.DoesNotExist:
            return redirect('/404/')


class BookChapterView(DetailView):
    template_name = 'books/bookchapter.html'

    @vary_on_headers('X-Requested-With')
    def get(self, request, *args, **kwargs):
        try:
            b_chap = BookChapter.objects.select_related('book').get(book__slug=kwargs['book_slug'], c_id=kwargs['c_id'])
            b_chaps = BookChapter.objects.filter(book__slug=kwargs['book_slug']).values('c_id', 'title', 'created').order_by('c_id')
            for chap in b_chaps:
                url = reverse('books:bookchapter', kwargs={'book_slug': b_chap.book.slug, 'c_id': chap['c_id']})
                chap.update({'absolute_url': url})

            try:
                prev_chap = b_chaps[kwargs['c_id'] - 2:kwargs['c_id'] - 1][0]
            except (IndexError, AssertionError):
                prev_chap = None
            try:
                next_chap = b_chaps[kwargs['c_id']:kwargs['c_id'] + 2][0]
            except IndexError:
                next_chap = None

            if request.is_ajax():
                data = {}
                template_name = 'books/bookchapter_chap_nav.html'
                context = {'b_chap': b_chap, 'b_chaps': b_chaps}
                data['html_chaps'] = render_to_string(
                    template_name,
                    context=context,
                    request=request
                )
                return JsonResponse(data)

            context = {
                'b_chap': b_chap,
                'prev_chap': prev_chap,
                'next_chap': next_chap,
            }

            if request.user.is_authenticated:
                context['user_lib'] = list(request.user.library.book.all())
                try:
                    book_prog = BookProgress.objects.get(user=request.user, book=b_chap.book)
                    if book_prog.c_id != b_chap.c_id:
                        book_prog.c_id = b_chap.c_id
                        book_prog.save()
                except BookProgress.DoesNotExist:
                    BookProgress.objects.create(
                        book=b_chap.book,
                        user=request.user,
                        c_id=b_chap.c_id,
                    )
            return render(request, template_name=self.template_name, context=context)
        except (Book.DoesNotExist, BookChapter.DoesNotExist):
            return redirect('/404/')


class BookRankingView(ListView):
    template_name = 'books/bookranking.html'
    queryset = Book.objects.published().filter(ranking__gt=0).order_by('ranking')
    context_object_name = 'books_all'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = list(self.queryset.iterator())
        user_auth = self.request.user.is_authenticated
        books = qs[3:]
        books_top = qs[:3]
        paginator = Paginator(books, 7)
        page = self.request.GET.get('page')
        books = paginator.get_page(page)
        context = {
            'books': books, 'books_top': books_top,
            'page_title': 'Ranking',
            'user_auth': user_auth,
        }
        if user_auth:
            user_lib = list(self.request.user.library.book.all())
            context['user_lib'] = user_lib
        return context


class BookSearchView(ListView):
    template_name = 'books/booksearch.html'
    form = BookSearchForm
    context = {'form': form, 'page_title': 'Search Books'}

    def get(self, request, **kwargs):
        form = self.form(request.GET)
        context = dict(self.context)  # update get view context
        context['form'] = form

        if request.is_ajax():
            data = {}
            template_name = 'books/booksearch-result.html'
            search_field = request.GET.get('search_field', None)

            if not search_field:
                # handle ajax error
                return JsonResponse(data, status=403)

novel/comments/views.py
from django.shortcuts import render

# Create your views here.

novel/templates/users/book_libcard_list.html
{% load static %}

<div class="row js-livesearch-container">
  {% for book in books %}
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12 js-livesearch-item">

      {% for b_prog in bookprogresses %}
        {% if b_prog.book_id == book.pk %}
        {% endif %}
      {% endfor %}
      <div class="libcard">
        <div class="libcard__nav">
          <button class="btn js-toggle-next">
            <i class="fas fa-ellipsis-v"></i>
          </button>
          <div class="js-toggle-content" style="display: none;">
            <button
              type="submit" class="btn js-lib-btn"
              data-lib-url="{% url 'users:lib-add-remove-ajax' book.slug %}"
              data-lib-in=1
              data-lib-remonly=true>
              <i class="fas fa-trash-alt"></i>
              <span>Remove</span>
            </button>
          </div>
        </div>
      {% if book.pk in prog_book_ids  %}
        {% for b_prog in bookprogresses %}
          {% if b_prog.book_id == book.pk %}
            <a class="libcard__link" href="{% url 'books:bookchapter' book.slug b_prog.c_id %}">
          {% endif %}
        {% endfor %}
      {% else %}
        {% if book.chapters_count %}
          <a class="libcard__link" href="{% url 'books:bookchapter' book.slug 1 %}">
        {% else %}
          <a class="libcard__link" href="{% url 'books:book' book.slug %}">
        {% endif %}
      {% endif %}
          <div class="libcard__poster">
              <img class="libcard__poster--image" src="{{book.poster.url}}" alt="{{book.title}}">
          </div>
          <div class="libcard__info">
            <div class="libcard__info--title"><h4 class="h4-title">{{book.title|truncatewords:5}}</h4></div>
            <div class="libcard__info--chaps">
              {% if book.pk in prog_book_ids  %}
                {% for b_prog in bookprogresses %}
                  {% if b_prog.book_id == book.pk %}
                    Progress {{b_prog.c_id}} / {{book.chapters_count}}
                  {% endif %}
                {% endfor %}
              {% else %}
                Progress 0 / {{book.chapters_count}}
              {% endif %}
            </div>
          </div>
        </a>
      </div>
    </div>
  {% endfor %}
</div>

novel/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

novel/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
<div class="container">
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

novel/templates/users/user_library.html
{% extends "base.html" %}
{% load static %}

{% block title %}Library - {{block.super}}{% endblock %}

{% block content %}

{% include 'components/csrf_gen_form.html' %}

<div class="container">
  <div class="librowse mt-30">
    <div class="librowse__title">
      <h1 class="h1-title">Library</h1>
      <input class="form-control js-livesearch-input" type="text" placeholder="Search Book">
    </div>
    <div class="librowse__books">
      {% include 'users/book_libcard_list.html' %}
    </div>
  </div>
</div>
{% endblock content %}

novel/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}